
package Telas;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

/**
 *
 * @author Leonardo
 */
public class Carregamento extends javax.swing.JFrame {
    
    /**
     * Creates new form Carregamento
     */
    public Carregamento() {
        initComponents();
        mostraJogos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlCarregamento = new javax.swing.JPanel();
        jLblEscolhaJogo = new javax.swing.JLabel();
        jBtnVoltaMenu = new javax.swing.JButton();
        jCBoxJogos = new javax.swing.JComboBox<>();
        jTxtDescricaoJogo = new javax.swing.JTextArea();
        jBtnIniciaJogo = new javax.swing.JButton();

        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(400, 500));

        jPnlCarregamento.setBackground(new java.awt.Color(34, 34, 167));
        jPnlCarregamento.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLblEscolhaJogo.setFont(new java.awt.Font("Charlemagne Std", 1, 14)); // NOI18N
        jLblEscolhaJogo.setForeground(new java.awt.Color(231, 235, 88));
        jLblEscolhaJogo.setText("Escolha o Jogo");

        jBtnVoltaMenu.setFont(new java.awt.Font("Charlemagne Std", 1, 12)); // NOI18N
        jBtnVoltaMenu.setText("Voltar ao Menu");
        jBtnVoltaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVoltaMenuActionPerformed(evt);
            }
        });

        jCBoxJogos.setFont(new java.awt.Font("Charlemagne Std", 1, 12)); // NOI18N
        jCBoxJogos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jogo 1", "Jogo 2", "Jogo 3", "Jogo 4" }));

        jTxtDescricaoJogo.setEditable(false);
        jTxtDescricaoJogo.setBackground(new java.awt.Color(5, 5, 99));
        jTxtDescricaoJogo.setColumns(20);
        jTxtDescricaoJogo.setFont(new java.awt.Font("Charlemagne Std", 1, 12)); // NOI18N
        jTxtDescricaoJogo.setForeground(new java.awt.Color(252, 247, 103));
        jTxtDescricaoJogo.setRows(5);

        jBtnIniciaJogo.setFont(new java.awt.Font("Charlemagne Std", 1, 12)); // NOI18N
        jBtnIniciaJogo.setText("Iniciar Jogo");
        jBtnIniciaJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIniciaJogoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlCarregamentoLayout = new javax.swing.GroupLayout(jPnlCarregamento);
        jPnlCarregamento.setLayout(jPnlCarregamentoLayout);
        jPnlCarregamentoLayout.setHorizontalGroup(
            jPnlCarregamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlCarregamentoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jBtnIniciaJogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnVoltaMenu)
                .addGap(20, 20, 20))
            .addGroup(jPnlCarregamentoLayout.createSequentialGroup()
                .addGroup(jPnlCarregamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlCarregamentoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCBoxJogos, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtDescricaoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlCarregamentoLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLblEscolhaJogo)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPnlCarregamentoLayout.setVerticalGroup(
            jPnlCarregamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlCarregamentoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLblEscolhaJogo)
                .addGroup(jPnlCarregamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlCarregamentoLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jCBoxJogos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlCarregamentoLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jTxtDescricaoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPnlCarregamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnVoltaMenu)
                    .addComponent(jBtnIniciaJogo))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlCarregamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlCarregamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnVoltaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVoltaMenuActionPerformed
       this.dispose();
       TelaInicial telaInicio = new TelaInicial();
       telaInicio.setLocationRelativeTo(null);
       telaInicio.setVisible(true);
      
    }//GEN-LAST:event_jBtnVoltaMenuActionPerformed

    private void jBtnIniciaJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIniciaJogoActionPerformed
        JogoPrincipal telaJogo = new JogoPrincipal();
        this.dispose();
        telaJogo.setVisible(true);
        telaJogo.setLocationRelativeTo(null);
    }//GEN-LAST:event_jBtnIniciaJogoActionPerformed
    
    private void mostraJogos(){
        String textoDefault = "Texto: ";
        String textoM = jCBoxJogos.getSelectedItem().toString();
        jTxtDescricaoJogo.setText(textoDefault + textoM);
        jCBoxJogos.addItemListener(new ItemListener(){
            @Override
            public void itemStateChanged(ItemEvent e){
                if(e.getStateChange()==ItemEvent.SELECTED){
                    String texto = jCBoxJogos.getSelectedItem().toString();
                    String str = "Texto: ";
                    str = str + texto;
                    jTxtDescricaoJogo.setText(str);
                }
            }

            
        });
    }
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carregamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carregamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carregamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carregamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Carregamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnIniciaJogo;
    private javax.swing.JButton jBtnVoltaMenu;
    private javax.swing.JComboBox<String> jCBoxJogos;
    private javax.swing.JLabel jLblEscolhaJogo;
    private javax.swing.JPanel jPnlCarregamento;
    private javax.swing.JTextArea jTxtDescricaoJogo;
    // End of variables declaration//GEN-END:variables
}
