/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.JOptionPane;

/**
 *
 * @author brunolebar
 */
public class Local extends javax.swing.JFrame {

    /**
     * Creates new form Local
     */
    public Local() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlLocal = new javax.swing.JPanel();
        jLblNome = new javax.swing.JLabel();
        jBtnSalvarSair = new javax.swing.JButton();
        jBtnPersonagem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jBtnEvento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPnlLocal.setBackground(new java.awt.Color(34, 34, 167));
        jPnlLocal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLblNome.setFont(new java.awt.Font("Charlemagne Std", 1, 18)); // NOI18N
        jLblNome.setForeground(new java.awt.Color(255, 255, 88));
        jLblNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblNome.setText("Nome");
        jLblNome.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPnlLocal.add(jLblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 186, -1));

        jBtnSalvarSair.setFont(new java.awt.Font("Charlemagne Std", 1, 12)); // NOI18N
        jBtnSalvarSair.setText("Salvar e Sair");
        jBtnSalvarSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarSairActionPerformed(evt);
            }
        });
        jPnlLocal.add(jBtnSalvarSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, -1));

        jBtnPersonagem.setFont(new java.awt.Font("Charlemagne Std", 1, 12)); // NOI18N
        jBtnPersonagem.setText("Personagem");
        jBtnPersonagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPersonagemActionPerformed(evt);
            }
        });
        jPnlLocal.add(jBtnPersonagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        jList1.setFont(new java.awt.Font("Courier", 1, 12)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jPnlLocal.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 220, 180));

        jBtnEvento.setFont(new java.awt.Font("Charlemagne Std", 0, 13)); // NOI18N
        jBtnEvento.setText("Evento");
        jBtnEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEventoActionPerformed(evt);
            }
        });
        jPnlLocal.add(jBtnEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlLocal, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlLocal, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnPersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPersonagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnPersonagemActionPerformed

    private void jBtnEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEventoActionPerformed
        JOptionPane.showMessageDialog(null,jList1.getSelectedValue());
    }//GEN-LAST:event_jBtnEventoActionPerformed

    private void jBtnSalvarSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSalvarSairActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnEvento;
    private javax.swing.JButton jBtnPersonagem;
    private javax.swing.JButton jBtnSalvarSair;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPnlLocal;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
